name: reVReports
channels:
    - conda-forge
    - nrel
dependencies:
    - python=3.12
    - pandas>=2.1.2,<3.0
    - click>=8.1.7,<9
    - numpy>=2.0.2,<3
    - matplotlib>=3.8.1,<4.0
    - seaborn>=0.13.0,<1.0
    - tqdm>=4.66.1,<5.0
    - pydantic>=2.4.2,<3.0
    - tabulate>=0.9.0,<1.0
    - cartopy>=0.24,<0.25
    - geopandas>=1.0.1,<1.1
    - pyproj>=3.3.0,<4
    - shapely>=2.0.7,<3
    - geoplot>=0.5.1,<1
    - pip>=23.3.1,<24.0
    - pip:
        - -r requirements.txt
