name: Upload to PyPi

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
        # IMPORTANT: this permission is mandatory for trusted publishing
        id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 1

    - name: Install Conda environment from environment.yml
      uses: mamba-org/setup-micromamba@main
      with:
        environment-file: environment.yml
        cache-environment: true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install "build>=1.2.2,<2"
        python -m pip install "pkginfo>=1.10.0,<2"
        python -m pip install "twine>=6.1.0,<7"
        python -m pip install .

    - name: Build a binary wheel
      run: |
        python -m build --sdist --wheel --outdir dist/ .

    - name: Check distribution files
      run: |
        twine check dist/*

    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
